# Generated by Django 3.1.7 on 2021-03-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('S_ID', models.CharField(default=None, max_length=8, primary_key=True, serialize=False)),
                ('C_Name', models.CharField(default=None, max_length=100)),
                ('Principal', models.CharField(default=None, max_length=50)),
                ('Phone', models.CharField(default=None, max_length=12)),
                ('Mail', models.EmailField(default=None, max_length=254)),
                ('PWD', models.BinaryField()),
                ('Salt', models.BinaryField()),
                ('Active', models.BooleanField(default=False)),
                ('Address', models.CharField(default=None, max_length=100)),
                ('Picture', models.ImageField(blank=True, default=None, upload_to='brand/')),
            ],
        ),
    ]
