# Generated by Django 3.1.7 on 2021-04-11 04:34

from django.db import migrations, models
import django.db.models.deletion
import supplier.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ID', models.CharField(default=None, max_length=12, primary_key=True, serialize=False)),
                ('Name', models.CharField(default=None, max_length=50)),
                ('Price', models.IntegerField(default=None)),
                ('Genre', models.CharField(choices=[('男士', '男士'), ('女士', '女士'), ('孩童', '孩童'), ('嬰幼兒', '嬰幼兒'), ('孕婦', '孕婦')], default=None, max_length=10)),
                ('Category', models.CharField(choices=[('上衣類', '上衣類'), ('襯衫類', '襯衫類'), ('內衣類', '內衣類'), ('外套類', '外套類'), ('下身類', '下身類'), ('配件類', '配件類'), ('洋裝類', '洋裝類'), ('運動類', '運動類'), ('鞋類', '鞋類')], default=None, max_length=10)),
                ('Sale_Category', models.CharField(default=None, max_length=10)),
                ('Description', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('SKU_ID', models.CharField(default=None, max_length=14, primary_key=True, serialize=False)),
                ('Color', models.CharField(choices=[('red', '紅'), ('orange', '橙'), ('yellow', '黃'), ('pink', '粉紅'), ('cyan', '青'), ('blue', '藍'), ('purple', '紫'), ('green', '綠'), ('gray', '灰'), ('black', '黑'), ('white', '白'), ('brown', '咖啡')], default=None, max_length=8)),
                ('Picture', models.ImageField(upload_to=supplier.models.product_pic_url)),
                ('Product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='supplier.product')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('S_ID', models.CharField(default=None, max_length=8, primary_key=True, serialize=False)),
                ('C_Name', models.CharField(default=None, max_length=100)),
                ('Principal', models.CharField(default=None, max_length=50)),
                ('Phone', models.CharField(default=None, max_length=12)),
                ('Mail', models.EmailField(default=None, max_length=254)),
                ('PWD', models.BinaryField()),
                ('Salt', models.BinaryField()),
                ('Active', models.BooleanField(default=False)),
                ('Address', models.CharField(default=None, max_length=100)),
                ('Picture', models.ImageField(blank=True, default=None, upload_to='brand/')),
            ],
        ),
        migrations.CreateModel(
            name='Stored',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default=None, max_length=8)),
                ('stored', models.IntegerField(default=None)),
                ('sku', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='supplier.sku')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Brand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
    ]
