# Generated by Django 3.1.7 on 2021-03-30 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(default=None, max_length=50)),
                ('Name', models.CharField(default=None, max_length=50)),
                ('Price', models.IntegerField(default=None, max_length=5)),
                ('Genre', models.CharField(choices=[], default=None, max_length=10)),
                ('Category', models.CharField(choices=[], default=None, max_length=10)),
                ('Sale_Category', models.CharField(default=None, max_length=10)),
                ('Brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU_ID', models.CharField(default=None, max_length=100)),
                ('Color', models.CharField(choices=[('red', '紅'), ('orange', '橙'), ('yellow', '黃'), ('pink', '粉紅'), ('cyan', '青'), ('blue', '藍'), ('purple', '紫'), ('green', '綠'), ('gray', '灰'), ('black', '黑'), ('white', '白'), ('brown', '咖啡')], default=None, max_length=8)),
                ('Picture', models.ImageField(upload_to='product/%s/%s')),
                ('O_Product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='supplier.product')),
            ],
        ),
        migrations.CreateModel(
            name='Stored',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.CharField(choices=[], default=None, max_length=5)),
                ('Stored', models.IntegerField(default=None, max_length=10)),
                ('sku', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='supplier.sku')),
            ],
        ),
    ]
