# Generated by Django 3.1.7 on 2021-03-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_product_sku_stored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='stored',
            name='Stored',
            field=models.IntegerField(default=None),
        ),
    ]
