# Generated by Django 3.1.7 on 2021-03-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20210318_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='Picture',
            field=models.ImageField(blank=True, default=None, upload_to='brand/'),
        ),
    ]
