# Generated by Django 3.1.7 on 2021-04-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_auto_20210330_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='O_Product',
            new_name='Product',
        ),
        migrations.AlterField(
            model_name='sku',
            name='Picture',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
