# Generated by Django 3.1.7 on 2021-04-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_auto_20210401_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(choices=[('top', '上衣類'), ('shirt', '襯衫類'), ('undies', '內衣類'), ('coat', '外套類'), ('pants', '下身類'), ('accessories', '配件類'), ('dress', '洋裝類'), ('sport', '運動類'), ('shoes', '鞋類')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='Genre',
            field=models.CharField(choices=[('MEN', '男士'), ('WOMEN', '女士'), ('KIDS', '孩童'), ('BABY', '嬰幼兒'), ('Pregnant', '孕婦')], default=None, max_length=10),
        ),
    ]
