# Generated by Django 3.1.7 on 2021-04-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_auto_20210402_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stored',
            name='Size',
            field=models.IntegerField(default=None),
        ),
    ]
