# Generated by Django 3.1.7 on 2021-04-02 13:14

from django.db import migrations, models
import supplier.models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_auto_20210402_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='Picture',
            field=models.ImageField(upload_to=supplier.models.product_pic_url),
        ),
    ]
