# Generated by Django 3.1.7 on 2021-04-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_auto_20210402_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(choices=[('上衣類', '上衣類'), ('襯衫類', '襯衫類'), ('內衣類', '內衣類'), ('外套類', '外套類'), ('下身類', '下身類'), ('配件類', '配件類'), ('洋裝類', '洋裝類'), ('運動類', '運動類'), ('鞋類', '鞋類')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='Genre',
            field=models.CharField(choices=[('男士', '男士'), ('女士', '女士'), ('孩童', '孩童'), ('嬰幼兒', '嬰幼兒'), ('孕婦', '孕婦')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='ID',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='sku',
            name='SKU_ID',
            field=models.CharField(default=None, max_length=14),
        ),
        migrations.AlterField(
            model_name='stored',
            name='Size',
            field=models.IntegerField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default=None, max_length=8),
        ),
    ]
