# Generated by Django 3.1.7 on 2021-04-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0008_auto_20210402_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stored',
            name='Size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default=None, max_length=8),
        ),
    ]
