# Generated by Django 3.1.7 on 2021-04-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0009_auto_20210404_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stored',
            old_name='Stored',
            new_name='stored',
        ),
    ]
