# Generated by Django 3.1.7 on 2021-04-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes2You_User',
            fields=[
                ('Mail', models.EmailField(default=None, max_length=254, primary_key=True, serialize=False)),
                ('Name', models.CharField(default=None, max_length=50)),
                ('PWD', models.BinaryField()),
                ('Salt', models.BinaryField()),
                ('Active', models.BooleanField(default=False)),
                ('Phone_1', models.CharField(default=None, max_length=12)),
                ('Address', models.CharField(default='', max_length=100)),
                ('Gender', models.CharField(choices=[('男', 'Male'), ('女', 'Female'), ('不願透漏', 'Null')], default='N', max_length=10)),
            ],
        ),
    ]
