# Generated by Django 3.1.7 on 2021-03-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes2you_user',
            name='salt',
        ),
        migrations.AlterField(
            model_name='clothes2you_user',
            name='phone_1',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='clothes2you_user',
            name='phone_2',
            field=models.CharField(default='', max_length=12),
        ),
    ]
