# Generated by Django 3.1.7 on 2021-04-22 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_Car',
            fields=[
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.clothes2you_user')),
                ('number', models.IntegerField(default=None)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='supplier.stored')),
            ],
        ),
    ]
