# Generated by Django 3.1.7 on 2021-03-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210302_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes2you_user',
            old_name='phone_1',
            new_name='Phone_1',
        ),
        migrations.RenameField(
            model_name='clothes2you_user',
            old_name='phone_2',
            new_name='Phone_2',
        ),
        migrations.RemoveField(
            model_name='clothes2you_user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='clothes2you_user',
            name='user',
        ),
        migrations.AddField(
            model_name='clothes2you_user',
            name='Address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clothes2you_user',
            name='Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clothes2you_user',
            name='PWD',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='clothes2you_user',
            name='Salt',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='clothes2you_user',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
