# Generated by Django 3.1.7 on 2021-03-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210302_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes2you_user',
            name='Active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clothes2you_user',
            name='Mail',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
