# Generated by Django 3.1.7 on 2021-03-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210302_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes2you_user',
            name='PWD',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='clothes2you_user',
            name='Salt',
            field=models.BinaryField(),
        ),
    ]
