# Generated by Django 3.1.7 on 2021-03-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210304_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes2you_user',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Null')], default='N', max_length=1),
        ),
    ]
