# Generated by Django 3.1.7 on 2021-03-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_clothes2you_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes2you_user',
            name='Phone_2',
        ),
    ]
