# Generated by Django 3.1.7 on 2021-03-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_clothes2you_user_phone_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes2you_user',
            name='Address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='clothes2you_user',
            name='Mail',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='clothes2you_user',
            name='Name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='clothes2you_user',
            name='Phone_1',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
