# Generated by Django 3.1.7 on 2021-03-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210317_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes2you_user',
            name='Address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
